language: python
python: 
  - "3.6"

services: postgresql

env:
  - DJANGO=1.11.7
before_install:
  - export DJANGO_SETTINGS_MODULE=dev_team_app.settings
  - export PYTHONPATH=$HOME/builds/johnchuks/collabPRO-API
  - export PIP_USE_MIRRORS=true
  - export BUILD_ON_TRAVIS=true
install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

script:
  - python manage.py test




