version: '3'
services:
  db:
    image: postgres
    container_name: collabpro_db
    restart: always
    ports: 
      - "5433:5432"
    env_file:
      - .env
  web:
    container_name: collabpro_server
    build: 
      context: .
      dockerfile: ./docker/server/Dockerfile
    command: /start.sh
    env_file:
      - .env
    volumes:
      - .:/collabpro
      - static_volume:/collabpro/static
    depends_on:
      - db
    ports:
      - "9000:9000"
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 1337:80
    volumes:
      - static_volume:/collabpro/static
    depends_on:
      - web
volumes:
  static_volume:
